// The entries for the Bingo. May be modified but must be 
// at least 24 entries.
let bingoEntries = new Array(
	"Attention", 
	"Color theory",
	"Visual pop out",
	"Gestalt Rule - Common Region",
	"Gestalt Rule - Proximity",
	"Short-term memory",
	"7 ± 2 Memory",
	"Recognize than recall",
	"Fitt's Law",
	"Mental models",
	"Metaphor",
	"Affordance",
	"Gulfs of Execution and Evaluation",
	"Predictability",
	"Familiarity",
	"Consistency",
	"Substitutivity",
	"Dialog Initiative",
	"Multi-threading",
	"Observability",
	"Recoverability",
	"Visibility",
	"Transparency",
	"Gamification");
