// The entries for the Bingo. May be modified but must be 
// at least 24 entries.
let bingoEntries = new Array(
	"Animals Giving Birth", 
	"Clowns",
	"Exercise Video",
	"Unwarranted Nudity",
	"White Person Rapping",
	"Moral Panic",
	"Digestive system",
	"Car dealership",
	"Furniture store",
	"Sergery",
	"Humans Giving Birth",
	"Faded Celebrity",
	"Medical Jingle",
	"Puppets",
	"Obsolete Technology",
	"Off-Color Food",
	"Local News",
	"Dating",
	"Instructional Video",
	"Human/Animal Sexuality",
	"Synthesizer Music",
	"Flying Windows",
	"Organized Religion",
	"Crude CGI");